name: Tests

on:
  push:
    branches:
      - main
jobs:
    frontend:
      runs-on: ubuntu-latest
      steps:
        - name: go to frontend
          run: cd frontend
          shell: bash
        - name: run tests
          run:  npm run test
          shell: bash


